### ISSUE TITLE
Not Installing - Joomla 4

### ISSUE THREAD

**Issue by rev4670** [hoochicken/plg_editors-xtd_qlloremipsum#1]
Errors installing on localhoet

Warning
JInstaller: :Install: File does not exist [ROOT]\tmp\plg_editors-xtd_qlloremipsum-main\LICENCE.txt

Plugin Install: Could not copy files from the source.

danger
Error installing plugin

**Comment by hoochicken** [comment]
Thank you taking the time to write to me!

Oooooops, just fixed it. Download the new version:
https://github.com/hoochicken/plg_editors-xtd_qlloremipsum/archive/refs/tags/v2.0.3.zip
